
epochs: 10
batch_size: 32
root_dir: 


height: 28
width: 28
channels: 1

csv: True
checkpoint: True
early_stopping: false
tensorboard: False
lr : True 


learning_rate: 0.001
optimizer: Adam
loss: categorical_crossentropy
save_model_name : "Dncnn"
csv_log_dir: 'logs/csv_logs/'
csv_log_name: 'Dncnn.csv'
checkpoint_dir: 'logs/model_weights/'





